### ISSUE TITLE
Using gometalinter with CircleCI

### ISSUE THREAD

**Issue by fern4lvarez** [alecthomas/gometalinter#13]
Has anyone tried to use gometalinter within a CircleCI job?

This is my `circle.yml`:

```
dependencies:
    pre:
        - go get -u github.com/alecthomas/gometalinter
        - gometalinter --install

test:
    override:
        - gometalinter .
        - gometalinter ./cmd/rqlite-cli
        - gometalinter ./command
        - gometalinter ./db
        - gometalinter ./interfaces
        - gometalinter ./log
        - gometalinter ./server
        - go test -timeout 60s -v ./...
        - GORACE="halt_on_error=1" go test -race -timeout 120s -v ./...
```

The dependencies installation runs successfully:

```
$ go get -u github.com/alecthomas/gometalinter Exit code: 0
```

```
gometalinter --install

Installing errcheck -> go get github.com/alecthomas/errcheck
Installing varcheck -> go get github.com/opennota/check/cmd/varcheck
Installing structcheck -> go get github.com/opennota/check/cmd/structcheck
Installing vet -> go get golang.org/x/tools/cmd/vet
Installing gocyclo -> go get github.com/alecthomas/gocyclo
Installing go-nyet -> go get github.com/barakmich/go-nyet
Installing golint -> go get github.com/golang/lint/golint
Installing gotype -> go get golang.org/x/tools/cmd/gotype
Installing defercheck -> go get github.com/opennota/check/cmd/defercheck
Installing deadcode -> go get github.com/remyoudompheng/go-misc/deadcode 
```

It starts to fail when using gometalinter:

```
main.go:26:2:error: could not import github.com/otoolep/rqlite/log (can't find import: github.com/otoolep/rqlite/log) (gotype)
main.go:27:2:error: could not import github.com/otoolep/rqlite/server (can't find import: github.com/otoolep/rqlite/server) (gotype)
main.go:61:3:error: undeclared name: log (gotype)
main.go:64:4:error: undeclared name: log (gotype)
main.go:70:4:error: undeclared name: log (gotype)
main.go:77:2:error: undeclared name: log (gotype)
main.go:82:3:error: undeclared name: log (gotype)
main.go:83:3:error: undeclared name: log (gotype)
main.go:90:3:error: undeclared name: log (gotype)
main.go:97:7:error: undeclared name: server (gotype)
 main.go:27::warning: unused struct field 2: could not import github.com/otoolep/rqlite/server (/home/ubuntu/.go_workspace/src/github.com/otoolep/rqlite/server/server.go:20:2: could not import github.com/otoolep/rqlite/command (/home/ubuntu/.go_workspace/src/github.com/otoolep/rqlite/command/execute_command.go:5:2: could not import github.com/otoolep/rqlite/db (/home/ubuntu/.go_workspace/src/github.com/otoolep/rqlite/db/db.go:9:4: could not import github.com/mattn/go-sqlite3 (/home/ubuntu/.go_workspace/src/github.com/mattn/go-sqlite3/sqlite3_other.go:14:8: could not import C (build.Import failed: cannot find package "C" in any of: (structcheck)

main.go:27::warning: unused global variable 2: could not import github.com/otoolep/rqlite/server (/home/ubuntu/.go_workspace/src/github.com/otoolep/rqlite/server/server.go:20:2: could not import github.com/otoolep/rqlite/command (/home/ubuntu/.go_workspace/src/github.com/otoolep/rqlite/command/execute_command.go:5:2: could not import github.com/otoolep/rqlite/db (/home/ubuntu/.go_workspace/src/github.com/otoolep/rqlite/db/db.go:9:4: could not import github.com/mattn/go-sqlite3 (/home/ubuntu/.go_workspace/src/github.com/mattn/go-sqlite3/backup.go:12:8: could not import C (build.Import failed: cannot find package "C" in any of: (varcheck) gometalinter . returned exit code 1
```

Seems like gometalinter is not executed within a GOPATH. Does anyone have an idea?

You can find the full build here: https://circleci.com/gh/oscillatingworks/rqlite/3
