### ISSUE TITLE
vendor

### ISSUE THREAD

**Issue by fugr** [alecthomas/gometalinter#30]
gometalinter will support the import package in vendor feature in the future?

**Comment by fugr** [comment]
the packages real path is ../vendor/...


client/horus.go:10:2:error: could not import github.com/astaxie/beego (can't find import: github.com/astaxie/beego) (gotype)
client/horus.go:11:2:error: could not import github.com/astaxie/beego/httplib (can't find import: github.com/astaxie/beego/httplib) (gotype)
client/seed.go:11:2:error: could not import github.com/astaxie/beego/httplib (can't find import: github.com/astaxie/beego/httplib) (gotype)
client/horus.go:27:4:error: undeclared name: beego (gotype)
client/horus.go:42:3:error: undeclared name: beego (gotype)
client/horus.go:45:2:error: undeclared name: beego (gotype)
client/horus.go:51:9:error: undeclared name: httplib (gotype)
client/horus.go:71:9:error: undeclared name: httplib (gotype)
client/horus.go:93:9:error: undeclared name: httplib (gotype)
client/seed.go:133:9:error: undeclared name: httplib (gotype)
client/seed.go:156:9:error: undeclared name: httplib (gotype)
client/seed.go:190:9:error: undeclared name: httplib (gotype)
client/seed.go:216:9:error: undeclared name: httplib (gotype)
client/seed.go:242:9:error: undeclared name: httplib (gotype)

**Comment by alecthomas** [comment]
gometalinter shouldn't need to do anything to support vendoring. Did you try running with `GO_VENDOR=1 gometalinter .`?

You will also need to rebuild all the tools with 1.5: `gometalinter --update --install --force`

**Comment by fugr** [comment]
thanks

**Comment by alecthomas** [comment]
I'm assuming that worked, closing.

**Comment by alecthomas** [comment]
Actually, reopening to remind me to add it to the README

**Comment by kaiomagalhaes** [comment]
For some reason it isn't working on circleci:

```
machine:
  environment:
    # GOROOT is not set by default
    GOROOT: ""
    GOPATH: "${HOME}/.go_project"
    PATH: "${GOPATH}/bin:${PATH}"
    BUILD_PATH: "${GOPATH}/src/github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}"

dependencies:
  pre:
    - go get github.com/tools/godep
    - go get github.com/alecthomas/gometalinter

  override:
    - mkdir -p ~/.go_project/src/github.com/${CIRCLE_PROJECT_USERNAME}
    - ln -s ${HOME}/${CIRCLE_PROJECT_REPONAME} ${BUILD_PATH}

test:
  pre:
    - cd $BUILD_PATH && gometalinter --install
    - cd $BUILD_PATH && go vet $(go list ./... | grep -v /vendor/)
    - GO_VENDOR=1 cd $BUILD_PATH && gometalinter ./... | grep -v vendor
  override:
    - cd $BUILD_PATH && godep go test -v -race $(go list ./... | grep -v /vendor/)

```

It is throwing the same message. Any ideas?
